server:
  port: 80

eureka:
  instance:
    # 实例名字
    instance-id: cloud-order-openfegin-consumer80
  client:
    service-url:
      # 指定单机eureka server地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
spring:
  application:
    name: cloud-order-consumer
  # 分布式链路追踪
  sleuth:
      sampler:
        # 采样率的概率，100%采样
        probability: 1.0
        # 每秒采样数字最⾼为100
        rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      # rabbitmq地址
      queue: zipkin
      addresses: 192.168.66.101:5672


logging:
  pattern:
    console: logging.pattern.console=%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n
  level:
    com.itbaizhan.service: debug
    org.springframework.cloud.sleuth: debug
feign:
  client:
    config:
      default:
        # 连接超时
         connectTimeout: 2000
         # 读取数据超时时间
         readTimeout: 2000
