server:
  port: 8001
eureka:
  instance:
    # 实例名字
    instance-id: cloud-payment-provider8001
  client:
    service-url:
      #单机eureka 服务 地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
spring:
  application:
    # 设置应用名字
    name: cloud-payment-provider
    # 数据库配置
  datasource:
    name: sonice1024
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        minimum-idle: 3
        auto-commit: true
        idle-timeout: 10000
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1

logging:
  pattern:
    console: logging.pattern.console=%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n